- name: update repositories
  become: yes
  apt: update_cache=yes

- name: Installing JRE
  become: yes
  apt: name=default-jre state=present

- name: Installing JDK
  become: yes
  apt: name=default-jdk state=present

- name: adding Oracle PPA
  become: yes
  apt_repository: repo=ppa:webupd8team/java

- name: update repositories
  become: yes
  apt: update_cache=yes

- name: Installing java
  become: yes
  apt: name=oracle-{{java_version}}-installer state=present

- name: setting environmntal variable
  shell: echo JAVA_HOME is $JAVA_HOME
  environment: JAVA_HOME=/usr/lib/jvm/java-8-oracle
  register: shellout
- debug: var=shellout  

