- name: creting directory
  file: path=/opt/tomcat state=directory mode="u=rw,g=rw,o=rw"
  become: yes

- name: Download Tomcat
  get_url: url=http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.61/bin/apache-tomcat-7.0.61.tar.gz dest=/opt/apache-tomcat-7.0.61.tar.gz
  become: yes

- name: Downloading and unarchiving to desired directory
  unarchive: src=/opt/apache-tomcat-7.0.61.tar.gz dest=/opt/tomcat remote_src=True
  become: yes
