# - name: stop tomcat
#   command: sh {{ tomcat_path }}/shutdown.sh
#   become: yes
#   tags: start_tomcat

- name: stop tomcat
  shell: ./shutdown.sh
  args: chdir={{ tomcat_path }}
  become: yes
  tags: stop_tomcat

- name: copy the target
  copy: src=my_project-1.0-SNAPSHOT.jar dest=/opt/tomcat/apache-tomcat-7.0.61/webapps
  become: yes

# - name: start tomcat
#   command: sh {{ tomcat_path }}/startup.sh
#   become: yes
#   tags: start_tomcat

# - name: start tomcat  
#   shell: chdir={{ tomcat_path }}&&./startup.sh
#   tags: start_tomcat

- name: restart tomcat    
  shell: ./startup.sh
  args: chdir={{ tomcat_path }}
  become: yes
  tags: start_tomcat


