- name: stop tomcat
  command: sh {{ tomcat_path }}/shutdown.sh
  become: yes
  tags: start_tomcat

- name: copy the target
  copy: src=my_project-1.0-SNAPSHOT.jar dest=/opt/tomcat/apache-tomcat-7.0.61/webapps

- name: start tomcat
  command: sh {{ tomcat_path }}/startup.sh
  become: yes
  tags: start_tomcat
# - name: start tomcat  
#   shell: chdir={{ tomcat_path }}&&./startup.sh
#   tags: start_tomcat

# - name: stop tomcat
#   command: ./shutdown.sh
#   args: chdir={{ tomcat_path }}
#   tags: stop_tomcat

# - name: restart tomcat    
#   command: ./shutdown.sh && ./startup.sh
#   args: chdir={{ tomcat_path }}
#   tags: restart_tomcat


