- hosts: host
  tasks:
       - name: stop tomcat
         command: sh /opt/apache-tomcat-7.0.61/bin/shutdown.sh
         become: yes
  
       - name: copy the target
         become: yes
         copy: src=my_project-1.0-SNAPSHOT.jar dest=/opt/apache-tomcat-7.0.61/webapps

       - name: start tomcat
         command: ./startup.sh
           args: chdir=/opt/apache-tomcat-7.0.61/bin/
         become: yes
  
