- hosts: host
  tasks:
       - name: stop tomcat
         service: name=tomcat7 state=stopped
         become: yes
  
       - name: copy the target
         become: yes
         copy: src=my_project-1.0-SNAPSHOT.jar dest=/var/lib/tomcat7/webapps

       - name: start tomcat
         service: name=tomcat7 state=started
         become: yes
  
